version: '3.8'

services:
  app:
    build: .
    container_name: blog-app
    ports:
      - "9090:9090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/blog_app_apis
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=Akshay@123
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Akshay@123
      MYSQL_DATABASE: blog_app_apis
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: